---
- hosts: localhost
  tasks:
  - name: gathering cluster side configs as facts
    run_once: true
    delegate_to: "{{ ambari_host }}"
    ambari_component_facts:
      protocol: http
      port: 8080
      username: "{{ ambari_user }}"
      password: "{{ ambari_password }}"
      cluster_name: "{{ ambari_cluster_name }}"

- import_playbook: certs.yaml
- import_playbook: component_kafka.yaml
- import_playbook: component_accumulo.yaml
- import_playbook: component_nifi.yaml
