- name: update ambari property
  delegate_to: ambari_server
  command: >
    /var/lib/ambari-server/resources/scripts/configs.py
      -a set
      -l localhost
      -n {{ cluster_name }}
      -c {{ component_name }}
      -k {{ item.key }}
      -v {{ item.value }}
  loop:
    - lookup('dict', {{ component_props }})
  run_once: true
