ambari_component_name: kafka-broker
ambari_component_props:
  listeners: PLAINTEXT://localhost:6667,SSL://localhost:6666
  ssl.key.password: "{{ certs_jks_key_password }}"
  ssl.keystore.location: "{{ certs_dir }}/{{ certs_jks_file }}"
  ssl.keystore.password: "{{ certs_jks_store_password }}"
  ssl.keystore.type: JKS
  ssl.truststore.location: "{{ certs_dir }}/{{ certs_jks_file }}"
  ssl.truststore.password: "{{ certs_jks_store_password }}"
  ssl.truststore.type: JKS