- name: update ambari property for {{ ambari_component_name }}
  delegate_to: '{{ ambari_host }}'
  run_once: true
  ambari_cluster_config:
    protocol: http
    host: localhost
    port: 8080
    username: admin
    password: admin
    cluster_name: "{{ ambari_cluster_name }}"
    config_type: "{{ ambari_component_name }}"
    ignore_secret: true
    timeout_sec: 10
    config_map: |
       {% set local_dict = {}  %}
       {% for k in ambari_component_props %}
       {% set ret = local_dict.update( {k: {'value': ambari_component_props[k] } } ) %}
       {% endfor %}
       {{ local_dict|to_json }}



- name : restart stale components if needed
  delegate_to: localhost
  run_once: true
  uri:
    url: '{{ ambari_url }}/api/v1/clusters/{{ ambari_cluster_name }}/requests'
    body: "{{ lookup('template', 'restart.json.j2') }}"
    timeout: '{{ ambari_http_timeout }}'
    method: POST
    force_basic_auth: yes
    user: '{{ ambari_user }}'
    password: '{{ ambari_password }}'
    return_content: yes
    headers:
       X-Requested-By: ambari
       Content-Type: text/plain
    status_code: 201,202
    validate_certs: no
    body_format: json
  register: ambari_restart_request
  changed_when: ambari_restart_request.content
  notify: wait stale component restart
