# TODO: make property update idempotent
- name: update ambari property for {{ ambari_component_name }}
  delegate_to: '{{ ambari_host }}'
  run_once: true
  command: >
    /var/lib/ambari-server/resources/scripts/configs.py
      -a set
      -l localhost
      -n {{ ambari_cluster_name }}
      -c {{ ambari_component_name }}
      -k {{ item.key }}
      -v {{ item.value }}
  with_dict: '{{ ambari_component_props }}'

- name : restart stale components if needed
  delegate_to: localhost
  run_once: true
  uri:
    url: '{{ ambari_url }}/api/v1/clusters/{{ ambari_cluster_name }}/requests'
    body: "{{ lookup('template', 'restart.json.j2') }}"
    timeout: '{{ ambari_http_timeout }}'
    method: POST
    force_basic_auth: yes
    user: '{{ ambari_user }}'
    password: '{{ ambari_password }}'
    return_content: yes
    headers:
       X-Requested-By: ambari
       Content-Type: text/plain
    status_code: 201,202
    validate_certs: no
    body_format: json
  register: ambari_restart_request
  changed_when: ambari_restart_request.content
  notify: wait stale component restart
